openapi: 3.0.3
info:
  title: Laravel Task API
  description: CRUD - GET/POST/PUT/DELETE for Tasks
  version: "1.0.0"

servers:
  - url: http://localhost:8000

paths:
  /api/tasks:
    post:
      summary: Create a new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: First Task
                description:
                  type: string
                  example: This is the description of the First task.
      responses:
        "200":
          description: Task created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  description:
                    type: string
                  secure_token:
                    type: string

  /api/tasks/{taskId}:
    parameters:
      - name: taskId
        in: path
        required: true
        schema:
          type: string
        description: Task ID
    get:
      summary: Get a task by ID
      responses:
        "200":
          description: Task retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  description:
                    type: string
    put:
      summary: Update a task by ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Updated Task
                description:
                  type: string
                  example: This is the description of the update task.
                secure_token:
                  type: string
                  example: a4ba1215-21f3-4b77-8d9c-e6bfdab9a3dc
      responses:
        "200":
          description: Task updated successfully
    delete:
      summary: Delete a task by ID
      parameters:
        - name: secure_token
          in: query
          required: true
          schema:
            type: string
          description: Token to authorize deletion
      responses:
        "200":
          description: Task deleted successfully
